image: golang:latest

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/RajaSrinivasan/edev

stages:
  - test
  - build
  - deploy

format:
  script:
    - cd client; go test -v ./...
    - cd server; go test -v ./...
    
compile:
  stage: build
  script:
    - cd client; go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/client; cd ..
    - cd server; go build -race -ldflags "-extldflags '-static'" -o $CI_PROJECT_DIR/server; cd ..
  artifacts:
    paths:
      - $CI_PROJECT_DIR/client
      - $CI_PROJECT_DIR/server
