server:
    url: localhost
    port: 8689
    certfile: ../config/certfile
    privatekey: /Users/rajasrinivasan/.ssh/id_rsa
    htmlpath: ../config/html

client:
    name: AB3456
    uuid: 9542a93a-82e7-403f-8857-4c55fd38391a